version: '2'

services:
   nginx-proxy:
     image: jwilder/nginx-proxy
     build:
       context: ./docker
       dockerfile: proxy.dockerfile
     ports:
       - "80:80"
     volumes:
       - /var/run/docker.sock:/tmp/docker.sock:ro
     networks:
       - proxynet
   db:
     build:
       context: ./docker
       dockerfile: mysql.dockerfile
     volumes:
       - /var/lib/mysql
     restart: on-failure
     networks:
       - proxynet
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress

   wordpress:
     depends_on:
       - db
     build:
       context: ./docker
       dockerfile: wordpress.dockerfile
     volumes:
       - /var/www/html
       - ./docker/wp-content:/var/www/html/wp-content
     ports:
       - "80"
     restart: on-failure
     networks:
       - proxynet
     environment:
       VIRTUAL_HOST: localhost.localdomain,test.localhost.localdomain

networks:
  proxynet:
    driver: bridge
