version: '2'

services:
   nginx-proxy:
     image: jwilder/nginx-proxy
     ports:
       - "80:80"
     volumes:
       - /var/run/docker.sock:/tmp/docker.sock:ro
       - ./docker/config/nginx_ovrd.conf:/etc/nginx/conf.d/nginx_ovrd.conf
     networks:
       - proxynet
   db:
     build:
       context: ./docker
       dockerfile: mysql.dockerfile
     volumes:
       - /var/lib/mysql
     restart: on-failure
     networks:
       - proxynet
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress

   oese:
     depends_on:
       - db
     build:
       context: ./docker
       dockerfile: oese.dockerfile
     volumes:
       - /var/www/html
       - ./docker/wp-content:/var/www/html/wp-content
       - ./docker/config/php_ovrd.ini:/usr/local/etc/php/conf.d/php_ovrd.ini
     ports:
       - "80"
     restart: on-failure
     networks:
       - proxynet
     environment:
       VIRTUAL_HOST: localhost.localdomain,oet.localhost.localdomain,oese.localhost.localdomain,oii.localhost.localdomain
         
   solr:
     image: solr
     ports:
     - "8983"
     volumes:
     - /opt/solr/server/solr/mycores
     restart: on-failure

networks:
  proxynet:
    driver: bridge
