version: '2'

services:
   nginx-proxy:
     image: jwilder/nginx-proxy
     ports:
       - "80:80"
     volumes:
       - /var/run/docker.sock:/tmp/docker.sock:ro
     networks:
       - proxynet
   db:
     build:
       context: ./docker
       dockerfile: mysql.dockerfile
     volumes:
       - /var/lib/mysql
       - ./data/oese/:/docker-entrypoint-initdb.d
     restart: on-failure
     networks:
       - proxynet
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   oese:
     depends_on:
       - db
     build:
       context: ./docker
       dockerfile: oese.dockerfile
     volumes:
       - /var/www/html
     ports:
       - "80"
     restart: on-failure
     networks:
       - proxynet
     environment:
       VIRTUAL_HOST: oet.localhost.localdomain,oese.localhost.localdomain,oii.localhost.localdomain
       WORDPRESS_DB_HOST: db
       # connecting to db as mysql root allows auto-creation of new db
       WORDPRESS_DB_USER: root
       WORDPRESS_DB_PASSWORD: somewordpress
       WORDPRESS_DB_NAME: oese

   solr:
     image: solr
     ports:
     - "8983"
     volumes:
     - /opt/solr/server/solr/mycores
     restart: on-failure

networks:
  proxynet:
    driver: bridge
