version: '2'

services:
   nginx-proxy:
     image: jwilder/nginx-proxy
     ports:
       - "80:80"
     volumes:
       - /var/run/docker.sock:/tmp/docker.sock:ro
     networks:
       - proxynet
   db:
     build:
       context: ./docker
       dockerfile: mysql.dockerfile
     volumes:
       - /var/lib/mysql
     restart: on-failure
     networks:
       - proxynet
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress1:
     depends_on:
       - db
     build:
       context: ./docker
       dockerfile: wordpress.dockerfile
     volumes:
       - /var/www/html
     ports:
       - "80"
     restart: on-failure
     networks:
       - proxynet
     environment:
       VIRTUAL_HOST: wordpress1.local
       WORDPRESS_DB_HOST: db
       # connecting to db as mysql root allows auto-creation of new db
       WORDPRESS_DB_USER: root
       WORDPRESS_DB_PASSWORD: somewordpress
       WORDPRESS_DB_NAME: wordpress1

   solr:
     image: solr
     ports:
     - "8983"
     volumes:
     - /opt/solr/server/solr/mycores
     restart: on-failure

networks:
  proxynet:
    driver: bridge
