version: '2'

services:
   db:
     build:
       context: ./docker
       dockerfile: mysql.dockerfile
     volumes:
       - db_data:/var/lib/mysql
     restart: on-failure
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     build:
       context: ./docker
       dockerfile: wordpress.dockerfile
     volumes:
       - ./wp-content/plugins:/var/www/html/wp-content/plugins
       - ./wp-content/themes:/var/www/html/wp-content/themes
     ports:
       - "80:80"
     restart: on-failure
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
   solr:
     image: solr
     ports:
     - "8983:8983"
     volumes:
     - solr_data:/opt/solr/server/solr/mycores
     restart: on-failure
volumes:
    db_data:
      driver: local
    solr_data:
      driver: local
