version: '2'

services:
   db:
     image: mysql:5.7
     volumes:
       - /var/lib/mysql
       - ./docker/data:/docker-entrypoint-initdb.d
     restart: on-failure
     environment:
       MYSQL_DATABASE: wpoer
       MYSQL_ROOT_PASSWORD: somewordpress

   phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8982:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: somewordpress

   oer:
     depends_on:
       - db
     build:
       context: ./docker
       dockerfile: server-oer.dockerfile
     volumes:
       - /var/www/html
       - ./docker/wp-content:/var/www/html/wp-content
     ports:
       - "80"
     restart: on-failure
     environment:
       VIRTUAL_HOST: new-oer.test.navnorth.com test.navnorth.com

networks:
  default:
    external:
      name: docker_proxynet
